export { default as Processors } from './Processors.vue'
export { default as VideoCard } from './VideoCard.vue'
export { default as MPlate } from './MPlate.vue'
export { default as RAM } from './Ram.vue'
export { default as Bp } from './Bp.vue'
export { default as Case } from './Case.vue'
export { default as Ssd } from './Ssd.vue'
